_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.9
            "8":
                - 1
                - 5
            "12": 0.19.9
            "13": darwin-arm64
l1:
    value: 1e-06
l2:
    value: 1e-06
