wandb_version: 1

epochs:
  value: 150
l1:
  value: 5.0e-06
l2:
  value: 5.0e-06
learning_rate:
  value: 0.002
model_name:
  value: ANN_non_recurrent_with_LIF_output
optimizer:
  value: Adam
regularization:
  value: true
