_name:
    value: wandb.config
_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 16
                - 17
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.9
            "8":
                - 1
                - 5
            "12": 0.19.9
            "13": darwin-arm64
epochs:
    value: 150
l1:
    value: 5e-06
l2:
    value: 5e-06
learning_rate:
    value: 0.002
model_name:
    value: ANN_non_recurrent_with_LIF_output
optimizer:
    value: Adam
regularization:
    value: true
