wandb_version: 1

epochs:
  value: 150
l1:
  value: 1.0e-06
l2:
  value: 1.0e-05
learning_rate:
  value: 0.002
model_name:
  value: Hybrid_ANN_non_recurrent
optimizer:
  value: Adam
regularization:
  value: true
